trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/DTSPO-9061_tfcmt
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts (1)'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
    - plan
    - apply
    - destroy

  - name: environment_components
    type: object
    default:
    - deployment: 'ptlsbox_jenkins'
      environment: 'ptlsbox'
      component: 'jenkins'
      service_connection: 'OPS-APPROVAL-GATE-PTLSBOX-ENVS'
      dependsOn: 'Precheck'
    - deployment: 'sbox_jenkins'
      environment: 'sbox'
      component: 'subscription-base-infra'
      service_connection: 'DTS-SHAREDSERVICES-SBOX'
      dependsOn: 'Precheck'
    - deployment: 'ptl_jenkins'
      environment: 'ptl'
      component: 'jenkins'
      service_connection: 'OPS-APPROVAL-GATE-PTL-ENVS'
      dependsOn: 'Precheck'
    - deployment: 'prod_jenkins'
      environment: 'prod'
      component: 'subscription-base-infra'
      service_connection: 'DTS-SHAREDSERVICES-PROD'
      dependsOn: 'Precheck'
    - deployment: 'stg_jenkins'
      environment: 'stg'
      component: 'subscription-base-infra'
      service_connection: 'DTS-SHAREDSERVICES-STG'
      dependsOn: 'Precheck'
    - deployment: 'ithc_jenkins'
      environment: 'ithc'
      component: 'subscription-base-infra'
      service_connection: 'DTS-SHAREDSERVICES-ITHC'
      dependsOn: 'Precheck'
    - deployment: 'dev_jenkins'
      environment: 'dev'
      component: 'subscription-base-infra'
      service_connection: 'DTS-SHAREDSERVICES-DEV'
      dependsOn: 'Precheck'
    - deployment: 'demo_jenkins'
      environment: 'demo'
      component: 'subscription-base-infra'
      service_connection: 'DTS-SHAREDSERVICES-DEMO'
      dependsOn: 'Precheck'
    - deployment: 'test_jenkins'
      environment: 'test'
      component: 'subscription-base-infra'
      service_connection: 'DTS-SHAREDSERVICES-TEST'
      dependsOn: 'Precheck'


variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-18.04
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: sds-jenkins
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - script: echo Hello

  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          pool:
            vmImage: ${{ variables.agentPool }}
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
          - template: steps/terraform.yaml@cnp-azuredevops-libraries
            parameters:
              overrideAction: ${{ parameters.overrideAction }}
              environment: ${{ deployment.environment }}
              component: ${{ deployment.component }}
              serviceConnection: ${{ deployment.service_connection }}
              terraformInitSubscription: ${{ variables.terraformInitSubscription }}
              product: ${{ variables.product }}
